Exercise1-Code
efekarakayaOSF/Exercise1 pull request #1
Opened 2021-09-06 09:55 UTC by efekarakayaOSF

These 2 files, an apex page and class, are my exercise 1 implementation.

2021-09-06 14:25 UTC, aliozdemirosf requested changes

2021-09-06 14:25 UTC, aliozdemirosf commented on force-app/main/default/classes/AccountRelatedContactsExtension.cls
> +        receiveNewSearchTerm();
initially searchName is contact1 -> what is the purpose of this call?

2021-09-06 14:25 UTC, aliozdemirosf commented on force-app/main/default/classes/AccountRelatedContactsExtension.cls
> +    }
please check this article -> https://developer.salesforce.com/docs/atlas.en-us.soql_sosl.meta/soql_sosl/sforce_api_calls_soql_select_offset.htm

offset approach is correct but this process will consume unneeded process time and memory

2021-09-06 14:25 UTC, aliozdemirosf commented on force-app/main/default/classes/AccountRelatedContactsExtension.cls
> +    public List<Contact> getContacts() {
please add below description to all methods
```
/**
     * @author Ali Ozdemir
     * @date  August 25, 2021
     * @name initializeComponent
     * @description method to get record based on id with all fields
     * @param String
     * @return Product2
     */
```

2021-09-06 14:25 UTC, aliozdemirosf commented on force-app/main/default/classes/AccountRelatedContactsExtension.cls
> +
there is no need to make 2 separate query for this method

2021-09-06 14:33 UTC, efekarakayaOSF commented on force-app/main/default/classes/AccountRelatedContactsExtension.cls
> +        receiveNewSearchTerm();
The aim of that usage is trigger the function to prepare first display results according to pre-defined searchName value. I see function name and initial searchName are confusing at this moment.

2021-09-10 07:55 UTC, aliozdemirosf requested changes
Please include test class as well

2021-09-10 07:55 UTC, aliozdemirosf commented on force-app/main/default/classes/AccountRelatedContactsExtension.cls
> +        return result;
please wrap all queries and dmls with try-catch block

2021-09-10 07:55 UTC, aliozdemirosf commented on force-app/main/default/classes/AccountRelatedContactsExtension.cls
> +        return result;
this applies all occurances

2021-09-10 07:55 UTC, aliozdemirosf commented on force-app/main/default/classes/AccountRelatedContactsExtension.cls
> +		List<Contact> tempContacts = [SELECT Name, Is_Primary_Contact__c FROM Contact
I prefer using id instead of name for temp primary contact. there might be multiple contacts with same name and cause flow to fail by returning more rows than 2 eventhou there is only 1 primary contact

2021-09-10 07:55 UTC, aliozdemirosf commented on force-app/main/default/classes/AccountRelatedContactsExtension.cls
> +            }
this assignment is also not needed, with Id (or even with name) you can compare the temp one to another and set its value as true. after that rest as false.
this is only increase the heap size unnecessarily.

2021-09-10 07:55 UTC, aliozdemirosf commented on force-app/main/default/classes/AccountRelatedContactsExtension.cls
> +            update nextPrimaryContact;
we also have a dml limit, you shouldnt perform updates one by one but rather use list that you queried to update directly. to do so, as mentioned above, you need to change assignment logic and modify the records directly inside the loop

2021-09-13 08:48 UTC, aliozdemirosf requested changes

2021-09-13 08:48 UTC, aliozdemirosf commented on force-app/main/default/classes/AccountRelatedContactsExtension.cls
> +            update next;
Please do not perform step by step dml. I understood it is breaking your logic, then logic needs to be changed. as a best practice we need to keep dmls minimum cause we have limited dml right per transactions.

2021-09-15 08:17 UTC, merged